// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: play_service.proto

package server

import (
	context "context"
	encoding_binary "encoding/binary"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_619856292df9b42b, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return m.Size()
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type PlayRequest struct {
	AudioPath string `protobuf:"bytes,1,opt,name=audioPath,proto3" json:"audioPath,omitempty"`
}

func (m *PlayRequest) Reset()         { *m = PlayRequest{} }
func (m *PlayRequest) String() string { return proto.CompactTextString(m) }
func (*PlayRequest) ProtoMessage()    {}
func (*PlayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_619856292df9b42b, []int{1}
}
func (m *PlayRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PlayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PlayRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PlayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayRequest.Merge(m, src)
}
func (m *PlayRequest) XXX_Size() int {
	return m.Size()
}
func (m *PlayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayRequest proto.InternalMessageInfo

func (m *PlayRequest) GetAudioPath() string {
	if m != nil {
		return m.AudioPath
	}
	return ""
}

type VolumeRequest struct {
	Volume float32 `protobuf:"fixed32,1,opt,name=volume,proto3" json:"volume,omitempty"`
}

func (m *VolumeRequest) Reset()         { *m = VolumeRequest{} }
func (m *VolumeRequest) String() string { return proto.CompactTextString(m) }
func (*VolumeRequest) ProtoMessage()    {}
func (*VolumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_619856292df9b42b, []int{2}
}
func (m *VolumeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VolumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VolumeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VolumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeRequest.Merge(m, src)
}
func (m *VolumeRequest) XXX_Size() int {
	return m.Size()
}
func (m *VolumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeRequest proto.InternalMessageInfo

func (m *VolumeRequest) GetVolume() float32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

type SearchRequest struct {
	Input string `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_619856292df9b42b, []int{3}
}
func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return m.Size()
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

type PlayAudioInfo struct {
	Status   uint32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Duration int64   `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Curr     int64   `protobuf:"varint,3,opt,name=curr,proto3" json:"curr,omitempty"`
	Volume   float32 `protobuf:"fixed32,4,opt,name=volume,proto3" json:"volume,omitempty"`
	Mode     uint32  `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	Pathinfo string  `protobuf:"bytes,6,opt,name=pathinfo,proto3" json:"pathinfo,omitempty"`
	Name     string  `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *PlayAudioInfo) Reset()         { *m = PlayAudioInfo{} }
func (m *PlayAudioInfo) String() string { return proto.CompactTextString(m) }
func (*PlayAudioInfo) ProtoMessage()    {}
func (*PlayAudioInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_619856292df9b42b, []int{4}
}
func (m *PlayAudioInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PlayAudioInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PlayAudioInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PlayAudioInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayAudioInfo.Merge(m, src)
}
func (m *PlayAudioInfo) XXX_Size() int {
	return m.Size()
}
func (m *PlayAudioInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayAudioInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayAudioInfo proto.InternalMessageInfo

func (m *PlayAudioInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PlayAudioInfo) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *PlayAudioInfo) GetCurr() int64 {
	if m != nil {
		return m.Curr
	}
	return 0
}

func (m *PlayAudioInfo) GetVolume() float32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *PlayAudioInfo) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *PlayAudioInfo) GetPathinfo() string {
	if m != nil {
		return m.Pathinfo
	}
	return ""
}

func (m *PlayAudioInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type QueryReplay struct {
	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
}

func (m *QueryReplay) Reset()         { *m = QueryReplay{} }
func (m *QueryReplay) String() string { return proto.CompactTextString(m) }
func (*QueryReplay) ProtoMessage()    {}
func (*QueryReplay) Descriptor() ([]byte, []int) {
	return fileDescriptor_619856292df9b42b, []int{5}
}
func (m *QueryReplay) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReplay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReplay.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReplay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReplay.Merge(m, src)
}
func (m *QueryReplay) XXX_Size() int {
	return m.Size()
}
func (m *QueryReplay) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReplay.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReplay proto.InternalMessageInfo

func (m *QueryReplay) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type ProviderReply struct {
	ProviderType int32    `protobuf:"varint,1,opt,name=providerType,proto3" json:"providerType,omitempty"`
	Name         string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CurrDir      string   `protobuf:"bytes,3,opt,name=currDir,proto3" json:"currDir,omitempty"`
	Dirs         []string `protobuf:"bytes,4,rep,name=dirs,proto3" json:"dirs,omitempty"`
}

func (m *ProviderReply) Reset()         { *m = ProviderReply{} }
func (m *ProviderReply) String() string { return proto.CompactTextString(m) }
func (*ProviderReply) ProtoMessage()    {}
func (*ProviderReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_619856292df9b42b, []int{6}
}
func (m *ProviderReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProviderReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProviderReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProviderReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderReply.Merge(m, src)
}
func (m *ProviderReply) XXX_Size() int {
	return m.Size()
}
func (m *ProviderReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderReply.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderReply proto.InternalMessageInfo

func (m *ProviderReply) GetProviderType() int32 {
	if m != nil {
		return m.ProviderType
	}
	return 0
}

func (m *ProviderReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProviderReply) GetCurrDir() string {
	if m != nil {
		return m.CurrDir
	}
	return ""
}

func (m *ProviderReply) GetDirs() []string {
	if m != nil {
		return m.Dirs
	}
	return nil
}

type LocalProvider struct {
	Dirs []string `protobuf:"bytes,1,rep,name=dirs,proto3" json:"dirs,omitempty"`
}

func (m *LocalProvider) Reset()         { *m = LocalProvider{} }
func (m *LocalProvider) String() string { return proto.CompactTextString(m) }
func (*LocalProvider) ProtoMessage()    {}
func (*LocalProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_619856292df9b42b, []int{7}
}
func (m *LocalProvider) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LocalProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LocalProvider.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LocalProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalProvider.Merge(m, src)
}
func (m *LocalProvider) XXX_Size() int {
	return m.Size()
}
func (m *LocalProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalProvider.DiscardUnknown(m)
}

var xxx_messageInfo_LocalProvider proto.InternalMessageInfo

func (m *LocalProvider) GetDirs() []string {
	if m != nil {
		return m.Dirs
	}
	return nil
}

type PlayMode struct {
	Mode uint32 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (m *PlayMode) Reset()         { *m = PlayMode{} }
func (m *PlayMode) String() string { return proto.CompactTextString(m) }
func (*PlayMode) ProtoMessage()    {}
func (*PlayMode) Descriptor() ([]byte, []int) {
	return fileDescriptor_619856292df9b42b, []int{8}
}
func (m *PlayMode) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PlayMode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PlayMode.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PlayMode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayMode.Merge(m, src)
}
func (m *PlayMode) XXX_Size() int {
	return m.Size()
}
func (m *PlayMode) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayMode.DiscardUnknown(m)
}

var xxx_messageInfo_PlayMode proto.InternalMessageInfo

func (m *PlayMode) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

type Second struct {
	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Second) Reset()         { *m = Second{} }
func (m *Second) String() string { return proto.CompactTextString(m) }
func (*Second) ProtoMessage()    {}
func (*Second) Descriptor() ([]byte, []int) {
	return fileDescriptor_619856292df9b42b, []int{9}
}
func (m *Second) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Second) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Second.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Second) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Second.Merge(m, src)
}
func (m *Second) XXX_Size() int {
	return m.Size()
}
func (m *Second) XXX_DiscardUnknown() {
	xxx_messageInfo_Second.DiscardUnknown(m)
}

var xxx_messageInfo_Second proto.InternalMessageInfo

func (m *Second) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Dir struct {
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Dir) Reset()         { *m = Dir{} }
func (m *Dir) String() string { return proto.CompactTextString(m) }
func (*Dir) ProtoMessage()    {}
func (*Dir) Descriptor() ([]byte, []int) {
	return fileDescriptor_619856292df9b42b, []int{10}
}
func (m *Dir) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Dir) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Dir.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Dir) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dir.Merge(m, src)
}
func (m *Dir) XXX_Size() int {
	return m.Size()
}
func (m *Dir) XXX_DiscardUnknown() {
	xxx_messageInfo_Dir.DiscardUnknown(m)
}

var xxx_messageInfo_Dir proto.InternalMessageInfo

func (m *Dir) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "server.Empty")
	proto.RegisterType((*PlayRequest)(nil), "server.PlayRequest")
	proto.RegisterType((*VolumeRequest)(nil), "server.VolumeRequest")
	proto.RegisterType((*SearchRequest)(nil), "server.SearchRequest")
	proto.RegisterType((*PlayAudioInfo)(nil), "server.PlayAudioInfo")
	proto.RegisterType((*QueryReplay)(nil), "server.QueryReplay")
	proto.RegisterType((*ProviderReply)(nil), "server.ProviderReply")
	proto.RegisterType((*LocalProvider)(nil), "server.LocalProvider")
	proto.RegisterType((*PlayMode)(nil), "server.PlayMode")
	proto.RegisterType((*Second)(nil), "server.Second")
	proto.RegisterType((*Dir)(nil), "server.Dir")
}

func init() { proto.RegisterFile("play_service.proto", fileDescriptor_619856292df9b42b) }

var fileDescriptor_619856292df9b42b = []byte{
	// 593 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x6f, 0xd3, 0x30,
	0x18, 0x6e, 0xd6, 0x34, 0x6d, 0xdf, 0x12, 0x34, 0x99, 0x0f, 0x45, 0x03, 0x45, 0x93, 0x27, 0xb6,
	0x49, 0x48, 0x63, 0xda, 0x10, 0x07, 0x38, 0x0d, 0x8d, 0x03, 0xd2, 0x10, 0x21, 0x41, 0x5c, 0x91,
	0x69, 0x3c, 0x1a, 0x91, 0xc6, 0xc1, 0xb1, 0x2b, 0xe5, 0x3f, 0x70, 0xe0, 0xbf, 0xf0, 0x27, 0x38,
	0xee, 0xc8, 0x11, 0x6d, 0x7f, 0x04, 0xbd, 0x4e, 0x93, 0x26, 0x2b, 0x13, 0xdc, 0xfc, 0x3c, 0xef,
	0xe3, 0xf7, 0xdb, 0x06, 0x92, 0xa7, 0xac, 0xfc, 0x58, 0x70, 0xb9, 0x48, 0xa6, 0xfc, 0x20, 0x97,
	0x42, 0x09, 0xe2, 0x20, 0xe4, 0x92, 0x0e, 0x61, 0xf0, 0x6a, 0x9e, 0xab, 0x92, 0x3e, 0x86, 0x49,
	0x90, 0xb2, 0x32, 0xe4, 0x5f, 0x35, 0x2f, 0x14, 0x79, 0x08, 0x63, 0xa6, 0xe3, 0x44, 0x04, 0x4c,
	0xcd, 0x3c, 0x6b, 0xdb, 0xda, 0x1f, 0x87, 0x2b, 0x82, 0xee, 0x81, 0xfb, 0x41, 0xa4, 0x7a, 0xce,
	0x6b, 0xf9, 0x7d, 0x70, 0x16, 0x86, 0x30, 0xda, 0x8d, 0x70, 0x89, 0xe8, 0x23, 0x70, 0x23, 0xce,
	0xe4, 0x74, 0x56, 0x0b, 0xef, 0xc2, 0x20, 0xc9, 0x72, 0xad, 0x96, 0x3e, 0x2b, 0x40, 0x7f, 0x58,
	0xe0, 0x62, 0xf4, 0x13, 0x8c, 0xf0, 0x3a, 0x3b, 0x17, 0xe8, 0xb0, 0x50, 0x4c, 0xe9, 0xc2, 0x08,
	0xdd, 0x70, 0x89, 0xc8, 0x16, 0x8c, 0x62, 0x2d, 0x99, 0x4a, 0x44, 0xe6, 0x6d, 0x6c, 0x5b, 0xfb,
	0xfd, 0xb0, 0xc1, 0x84, 0x80, 0x3d, 0xd5, 0x52, 0x7a, 0x7d, 0xc3, 0x9b, 0x73, 0x2b, 0x31, 0xbb,
	0x9d, 0x18, 0x6a, 0xe7, 0x22, 0xe6, 0xde, 0xc0, 0x78, 0x37, 0x67, 0xf4, 0x9d, 0x33, 0x35, 0x4b,
	0xb2, 0x73, 0xe1, 0x39, 0x26, 0xbd, 0x06, 0xa3, 0x3e, 0x63, 0x73, 0xee, 0x0d, 0x0d, 0x6f, 0xce,
	0x74, 0x07, 0x26, 0xef, 0x34, 0x97, 0x65, 0xc8, 0xb1, 0xc1, 0x58, 0x1a, 0xd2, 0x98, 0x71, 0x1f,
	0x4b, 0x33, 0x80, 0x6a, 0x70, 0x03, 0x29, 0x16, 0x49, 0xcc, 0x25, 0xea, 0x4a, 0x42, 0xe1, 0x56,
	0xbe, 0x24, 0xde, 0x97, 0x79, 0xd5, 0xb0, 0x41, 0xd8, 0xe1, 0x9a, 0x68, 0x1b, 0xab, 0x68, 0xc4,
	0x83, 0x21, 0x56, 0x74, 0x9a, 0x54, 0x05, 0x8e, 0xc3, 0x1a, 0xa2, 0x3a, 0x4e, 0x64, 0xe1, 0xd9,
	0x26, 0xae, 0x39, 0xd3, 0x1d, 0x70, 0xcf, 0xc4, 0x94, 0xa5, 0x75, 0xec, 0x46, 0x64, 0xb5, 0x44,
	0x3e, 0x8c, 0xb0, 0xeb, 0x6f, 0xb0, 0xf8, 0xba, 0x21, 0xd6, 0xaa, 0x21, 0xd4, 0x07, 0x27, 0xe2,
	0x53, 0x91, 0xc5, 0x58, 0xdb, 0x82, 0xa5, 0xba, 0x32, 0xf7, 0xc3, 0x0a, 0xd0, 0x07, 0xd0, 0xc7,
	0xf8, 0x1d, 0xe3, 0x78, 0x69, 0x3c, 0xfa, 0x36, 0x00, 0x1b, 0xbd, 0x93, 0x17, 0xd5, 0x66, 0xbd,
	0x95, 0x01, 0xd3, 0x05, 0x27, 0x77, 0x0e, 0xaa, 0xd5, 0x3b, 0x68, 0xad, 0xdb, 0xd6, 0xbd, 0x36,
	0xd9, 0x6c, 0x01, 0xed, 0x91, 0x43, 0x70, 0xa2, 0x6a, 0xf2, 0x6e, 0x2d, 0x31, 0xfb, 0x7a, 0xf3,
	0x8d, 0x5d, 0xb0, 0x23, 0x25, 0xf2, 0xeb, 0xfa, 0x2e, 0x34, 0x9e, 0x27, 0x11, 0x57, 0x4d, 0xfd,
	0x9b, 0x6d, 0x7f, 0xc8, 0xac, 0xdf, 0x38, 0x82, 0x51, 0xd3, 0xce, 0x1b, 0xb3, 0x69, 0xcf, 0x9a,
	0xf6, 0xc8, 0x73, 0xd8, 0x8c, 0xb8, 0xea, 0x8e, 0xa2, 0x11, 0x77, 0xe8, 0xf5, 0x78, 0xbb, 0xd8,
	0x7e, 0x85, 0x1d, 0x9e, 0xd4, 0xa6, 0xd3, 0xe4, 0x2f, 0xba, 0x63, 0x18, 0x47, 0x5c, 0x55, 0x0f,
	0x72, 0xe5, 0xbc, 0xf3, 0x40, 0xd7, 0x2f, 0xed, 0x81, 0x1d, 0x71, 0xfe, 0x85, 0xdc, 0xae, 0x0d,
	0xd5, 0xa4, 0xd7, 0x85, 0x4f, 0x60, 0x78, 0x96, 0x14, 0xea, 0x24, 0x4d, 0xaf, 0x17, 0xdd, 0x4c,
	0xb2, 0xf5, 0x0a, 0x68, 0x8f, 0x3c, 0xc3, 0xb4, 0xf1, 0xcd, 0xaf, 0x72, 0xe9, 0xfc, 0x01, 0x37,
	0xdd, 0xdb, 0x05, 0x3b, 0x48, 0xb2, 0xcf, 0xff, 0x1c, 0xdc, 0x53, 0x18, 0x05, 0xba, 0x98, 0x99,
	0x6f, 0xe2, 0x3f, 0x97, 0xe2, 0xd0, 0x7a, 0xe9, 0xfd, 0xbc, 0xf4, 0xad, 0x8b, 0x4b, 0xdf, 0xfa,
	0x7d, 0xe9, 0x5b, 0xdf, 0xaf, 0xfc, 0xde, 0xc5, 0x95, 0xdf, 0xfb, 0x75, 0xe5, 0xf7, 0x3e, 0x39,
	0xe6, 0x47, 0x3c, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xce, 0xe0, 0xdf, 0x27, 0x05, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlayClient is the client API for Play service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlayClient interface {
	PlayOrPause(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (*PlayAudioInfo, error)
	Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PlayAudioInfo, error)
	Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	SetPlayMode(ctx context.Context, in *PlayMode, opts ...grpc.CallOption) (*Empty, error)
	Provider(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProviderReply, error)
	SetLocalProvider(ctx context.Context, in *LocalProvider, opts ...grpc.CallOption) (*Empty, error)
	SetDir(ctx context.Context, in *Dir, opts ...grpc.CallOption) (*Empty, error)
	SetVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Empty, error)
	Seek(ctx context.Context, in *Second, opts ...grpc.CallOption) (*Empty, error)
	ListAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*QueryReplay, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*QueryReplay, error)
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	PushInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Play_PushInfoClient, error)
}

type playClient struct {
	cc *grpc.ClientConn
}

func NewPlayClient(cc *grpc.ClientConn) PlayClient {
	return &playClient{cc}
}

func (c *playClient) PlayOrPause(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (*PlayAudioInfo, error) {
	out := new(PlayAudioInfo)
	err := c.cc.Invoke(ctx, "/server.Play/PlayOrPause", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playClient) Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PlayAudioInfo, error) {
	out := new(PlayAudioInfo)
	err := c.cc.Invoke(ctx, "/server.Play/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playClient) Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/server.Play/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playClient) SetPlayMode(ctx context.Context, in *PlayMode, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/server.Play/SetPlayMode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playClient) Provider(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProviderReply, error) {
	out := new(ProviderReply)
	err := c.cc.Invoke(ctx, "/server.Play/Provider", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playClient) SetLocalProvider(ctx context.Context, in *LocalProvider, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/server.Play/SetLocalProvider", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playClient) SetDir(ctx context.Context, in *Dir, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/server.Play/SetDir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playClient) SetVolume(ctx context.Context, in *VolumeRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/server.Play/SetVolume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playClient) Seek(ctx context.Context, in *Second, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/server.Play/Seek", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playClient) ListAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*QueryReplay, error) {
	out := new(QueryReplay)
	err := c.cc.Invoke(ctx, "/server.Play/ListAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*QueryReplay, error) {
	out := new(QueryReplay)
	err := c.cc.Invoke(ctx, "/server.Play/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/server.Play/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playClient) PushInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Play_PushInfoClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Play_serviceDesc.Streams[0], "/server.Play/PushInfo", opts...)
	if err != nil {
		return nil, err
	}
	x := &playPushInfoClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Play_PushInfoClient interface {
	Recv() (*PlayAudioInfo, error)
	grpc.ClientStream
}

type playPushInfoClient struct {
	grpc.ClientStream
}

func (x *playPushInfoClient) Recv() (*PlayAudioInfo, error) {
	m := new(PlayAudioInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PlayServer is the server API for Play service.
type PlayServer interface {
	PlayOrPause(context.Context, *PlayRequest) (*PlayAudioInfo, error)
	Status(context.Context, *Empty) (*PlayAudioInfo, error)
	Stop(context.Context, *Empty) (*Empty, error)
	SetPlayMode(context.Context, *PlayMode) (*Empty, error)
	Provider(context.Context, *Empty) (*ProviderReply, error)
	SetLocalProvider(context.Context, *LocalProvider) (*Empty, error)
	SetDir(context.Context, *Dir) (*Empty, error)
	SetVolume(context.Context, *VolumeRequest) (*Empty, error)
	Seek(context.Context, *Second) (*Empty, error)
	ListAll(context.Context, *Empty) (*QueryReplay, error)
	Search(context.Context, *SearchRequest) (*QueryReplay, error)
	Ping(context.Context, *Empty) (*Empty, error)
	PushInfo(*Empty, Play_PushInfoServer) error
}

// UnimplementedPlayServer can be embedded to have forward compatible implementations.
type UnimplementedPlayServer struct {
}

func (*UnimplementedPlayServer) PlayOrPause(ctx context.Context, req *PlayRequest) (*PlayAudioInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayOrPause not implemented")
}
func (*UnimplementedPlayServer) Status(ctx context.Context, req *Empty) (*PlayAudioInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (*UnimplementedPlayServer) Stop(ctx context.Context, req *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (*UnimplementedPlayServer) SetPlayMode(ctx context.Context, req *PlayMode) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPlayMode not implemented")
}
func (*UnimplementedPlayServer) Provider(ctx context.Context, req *Empty) (*ProviderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Provider not implemented")
}
func (*UnimplementedPlayServer) SetLocalProvider(ctx context.Context, req *LocalProvider) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLocalProvider not implemented")
}
func (*UnimplementedPlayServer) SetDir(ctx context.Context, req *Dir) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDir not implemented")
}
func (*UnimplementedPlayServer) SetVolume(ctx context.Context, req *VolumeRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVolume not implemented")
}
func (*UnimplementedPlayServer) Seek(ctx context.Context, req *Second) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Seek not implemented")
}
func (*UnimplementedPlayServer) ListAll(ctx context.Context, req *Empty) (*QueryReplay, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAll not implemented")
}
func (*UnimplementedPlayServer) Search(ctx context.Context, req *SearchRequest) (*QueryReplay, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedPlayServer) Ping(ctx context.Context, req *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedPlayServer) PushInfo(req *Empty, srv Play_PushInfoServer) error {
	return status.Errorf(codes.Unimplemented, "method PushInfo not implemented")
}

func RegisterPlayServer(s *grpc.Server, srv PlayServer) {
	s.RegisterService(&_Play_serviceDesc, srv)
}

func _Play_PlayOrPause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayServer).PlayOrPause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Play/PlayOrPause",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayServer).PlayOrPause(ctx, req.(*PlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Play_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Play/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayServer).Status(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Play_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Play/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayServer).Stop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Play_SetPlayMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayMode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayServer).SetPlayMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Play/SetPlayMode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayServer).SetPlayMode(ctx, req.(*PlayMode))
	}
	return interceptor(ctx, in, info, handler)
}

func _Play_Provider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayServer).Provider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Play/Provider",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayServer).Provider(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Play_SetLocalProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocalProvider)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayServer).SetLocalProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Play/SetLocalProvider",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayServer).SetLocalProvider(ctx, req.(*LocalProvider))
	}
	return interceptor(ctx, in, info, handler)
}

func _Play_SetDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Dir)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayServer).SetDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Play/SetDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayServer).SetDir(ctx, req.(*Dir))
	}
	return interceptor(ctx, in, info, handler)
}

func _Play_SetVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayServer).SetVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Play/SetVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayServer).SetVolume(ctx, req.(*VolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Play_Seek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Second)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayServer).Seek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Play/Seek",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayServer).Seek(ctx, req.(*Second))
	}
	return interceptor(ctx, in, info, handler)
}

func _Play_ListAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayServer).ListAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Play/ListAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayServer).ListAll(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Play_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Play/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Play_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Play/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Play_PushInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlayServer).PushInfo(m, &playPushInfoServer{stream})
}

type Play_PushInfoServer interface {
	Send(*PlayAudioInfo) error
	grpc.ServerStream
}

type playPushInfoServer struct {
	grpc.ServerStream
}

func (x *playPushInfoServer) Send(m *PlayAudioInfo) error {
	return x.ServerStream.SendMsg(m)
}

var _Play_serviceDesc = grpc.ServiceDesc{
	ServiceName: "server.Play",
	HandlerType: (*PlayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlayOrPause",
			Handler:    _Play_PlayOrPause_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Play_Status_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Play_Stop_Handler,
		},
		{
			MethodName: "SetPlayMode",
			Handler:    _Play_SetPlayMode_Handler,
		},
		{
			MethodName: "Provider",
			Handler:    _Play_Provider_Handler,
		},
		{
			MethodName: "SetLocalProvider",
			Handler:    _Play_SetLocalProvider_Handler,
		},
		{
			MethodName: "SetDir",
			Handler:    _Play_SetDir_Handler,
		},
		{
			MethodName: "SetVolume",
			Handler:    _Play_SetVolume_Handler,
		},
		{
			MethodName: "Seek",
			Handler:    _Play_Seek_Handler,
		},
		{
			MethodName: "ListAll",
			Handler:    _Play_ListAll_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Play_Search_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Play_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushInfo",
			Handler:       _Play_PushInfo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "play_service.proto",
}

func (m *Empty) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Empty) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Empty) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *PlayRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PlayRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PlayRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AudioPath) > 0 {
		i -= len(m.AudioPath)
		copy(dAtA[i:], m.AudioPath)
		i = encodeVarintPlayService(dAtA, i, uint64(len(m.AudioPath)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VolumeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VolumeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VolumeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Volume != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.Volume))))
		i--
		dAtA[i] = 0xd
	}
	return len(dAtA) - i, nil
}

func (m *SearchRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SearchRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SearchRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Input) > 0 {
		i -= len(m.Input)
		copy(dAtA[i:], m.Input)
		i = encodeVarintPlayService(dAtA, i, uint64(len(m.Input)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PlayAudioInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PlayAudioInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PlayAudioInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintPlayService(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Pathinfo) > 0 {
		i -= len(m.Pathinfo)
		copy(dAtA[i:], m.Pathinfo)
		i = encodeVarintPlayService(dAtA, i, uint64(len(m.Pathinfo)))
		i--
		dAtA[i] = 0x32
	}
	if m.Mode != 0 {
		i = encodeVarintPlayService(dAtA, i, uint64(m.Mode))
		i--
		dAtA[i] = 0x28
	}
	if m.Volume != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.Volume))))
		i--
		dAtA[i] = 0x25
	}
	if m.Curr != 0 {
		i = encodeVarintPlayService(dAtA, i, uint64(m.Curr))
		i--
		dAtA[i] = 0x18
	}
	if m.Duration != 0 {
		i = encodeVarintPlayService(dAtA, i, uint64(m.Duration))
		i--
		dAtA[i] = 0x10
	}
	if m.Status != 0 {
		i = encodeVarintPlayService(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryReplay) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReplay) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReplay) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Names) > 0 {
		for iNdEx := len(m.Names) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Names[iNdEx])
			copy(dAtA[i:], m.Names[iNdEx])
			i = encodeVarintPlayService(dAtA, i, uint64(len(m.Names[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ProviderReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProviderReply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProviderReply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Dirs) > 0 {
		for iNdEx := len(m.Dirs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Dirs[iNdEx])
			copy(dAtA[i:], m.Dirs[iNdEx])
			i = encodeVarintPlayService(dAtA, i, uint64(len(m.Dirs[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.CurrDir) > 0 {
		i -= len(m.CurrDir)
		copy(dAtA[i:], m.CurrDir)
		i = encodeVarintPlayService(dAtA, i, uint64(len(m.CurrDir)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintPlayService(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.ProviderType != 0 {
		i = encodeVarintPlayService(dAtA, i, uint64(m.ProviderType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *LocalProvider) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LocalProvider) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LocalProvider) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Dirs) > 0 {
		for iNdEx := len(m.Dirs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Dirs[iNdEx])
			copy(dAtA[i:], m.Dirs[iNdEx])
			i = encodeVarintPlayService(dAtA, i, uint64(len(m.Dirs[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *PlayMode) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PlayMode) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PlayMode) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Mode != 0 {
		i = encodeVarintPlayService(dAtA, i, uint64(m.Mode))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Second) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Second) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Second) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Value != 0 {
		i = encodeVarintPlayService(dAtA, i, uint64(m.Value))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Dir) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Dir) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Dir) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintPlayService(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPlayService(dAtA []byte, offset int, v uint64) int {
	offset -= sovPlayService(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Empty) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *PlayRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AudioPath)
	if l > 0 {
		n += 1 + l + sovPlayService(uint64(l))
	}
	return n
}

func (m *VolumeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Volume != 0 {
		n += 5
	}
	return n
}

func (m *SearchRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Input)
	if l > 0 {
		n += 1 + l + sovPlayService(uint64(l))
	}
	return n
}

func (m *PlayAudioInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovPlayService(uint64(m.Status))
	}
	if m.Duration != 0 {
		n += 1 + sovPlayService(uint64(m.Duration))
	}
	if m.Curr != 0 {
		n += 1 + sovPlayService(uint64(m.Curr))
	}
	if m.Volume != 0 {
		n += 5
	}
	if m.Mode != 0 {
		n += 1 + sovPlayService(uint64(m.Mode))
	}
	l = len(m.Pathinfo)
	if l > 0 {
		n += 1 + l + sovPlayService(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovPlayService(uint64(l))
	}
	return n
}

func (m *QueryReplay) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Names) > 0 {
		for _, s := range m.Names {
			l = len(s)
			n += 1 + l + sovPlayService(uint64(l))
		}
	}
	return n
}

func (m *ProviderReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProviderType != 0 {
		n += 1 + sovPlayService(uint64(m.ProviderType))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovPlayService(uint64(l))
	}
	l = len(m.CurrDir)
	if l > 0 {
		n += 1 + l + sovPlayService(uint64(l))
	}
	if len(m.Dirs) > 0 {
		for _, s := range m.Dirs {
			l = len(s)
			n += 1 + l + sovPlayService(uint64(l))
		}
	}
	return n
}

func (m *LocalProvider) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Dirs) > 0 {
		for _, s := range m.Dirs {
			l = len(s)
			n += 1 + l + sovPlayService(uint64(l))
		}
	}
	return n
}

func (m *PlayMode) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Mode != 0 {
		n += 1 + sovPlayService(uint64(m.Mode))
	}
	return n
}

func (m *Second) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Value != 0 {
		n += 1 + sovPlayService(uint64(m.Value))
	}
	return n
}

func (m *Dir) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovPlayService(uint64(l))
	}
	return n
}

func sovPlayService(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPlayService(x uint64) (n int) {
	return sovPlayService(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Empty) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Empty: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Empty: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPlayService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPlayService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPlayService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PlayRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PlayRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PlayRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AudioPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlayService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AudioPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPlayService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPlayService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPlayService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VolumeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VolumeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VolumeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Volume", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.Volume = float32(math.Float32frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipPlayService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPlayService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPlayService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SearchRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SearchRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SearchRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Input", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlayService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Input = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPlayService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPlayService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPlayService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PlayAudioInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PlayAudioInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PlayAudioInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			m.Duration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Duration |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Curr", wireType)
			}
			m.Curr = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Curr |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Volume", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.Volume = float32(math.Float32frombits(v))
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mode", wireType)
			}
			m.Mode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Mode |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pathinfo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlayService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pathinfo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlayService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPlayService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPlayService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPlayService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReplay) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReplay: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReplay: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Names", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlayService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Names = append(m.Names, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPlayService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPlayService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPlayService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProviderReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProviderReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProviderReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProviderType", wireType)
			}
			m.ProviderType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProviderType |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlayService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrDir", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlayService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurrDir = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dirs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlayService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Dirs = append(m.Dirs, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPlayService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPlayService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPlayService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LocalProvider) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LocalProvider: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LocalProvider: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dirs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlayService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Dirs = append(m.Dirs, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPlayService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPlayService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPlayService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PlayMode) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PlayMode: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PlayMode: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mode", wireType)
			}
			m.Mode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Mode |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPlayService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPlayService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPlayService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Second) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Second: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Second: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			m.Value = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Value |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPlayService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPlayService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPlayService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Dir) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Dir: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Dir: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlayService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPlayService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPlayService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPlayService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPlayService(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPlayService
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPlayService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPlayService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPlayService
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPlayService
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPlayService
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPlayService        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPlayService          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPlayService = fmt.Errorf("proto: unexpected end of group")
)
