package ui

const (
	_COUNT_DOWN_WIDTH   = 15
	_COUNT_DOWN_HEIGHT  = 3
	_PLAY_STATUS_HEIGHT = 11

	_HELP_BOX_WIDTH  = 30
	_HELP_BOX_HEIGHT = 12

	_SEARCH_HEIGHT = 3

	_VOLUME_HEIGHT = 0.5
	_VOLUME_WIDTH  = 0.08

	_PLAY_STATUS_WIDTH = 0.32
	_LIST_WIDTH        = 0.4

	_RIGHT_HELP_BOX_WIDTH = 0.2
)
